DROP TABLE VETERINARIOS IF EXISTS;
CREATE TABLE VETERINARIOS(
ID INT AUTO_INCREMENT PRIMARY KEY,
NROLICENCIA INT NOT NULL,
NOMBRE VARCHAR(25) NOT NULL,
APELLIDO VARCHAR(25) NOT NULL,
ESPECIALIDAD VARCHAR(50) NOT NULL
);

INSERT INTO VETERINARIOS VALUES(
DEFAULT, 23323, 'BRUNO', 'MARTINEZ', 'CARDIOLOGIA'
);